name: Discordtest
on: push 

jobs: 
  write-to-discord:
    runs-on: ubuntu-latest
    steps:
    - name: discord
      uses: sebastianpopp/discord-action@releases/v2
      with: 
        webhook: ${{ secrets.MYDISCORD_SECRETY }}
        message: jonatan2 has tested the connetction. 
    
  
